apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceOutline
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: MongoDB
    k8s.io/resource: mongodbs
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-mongodbs
spec:
  defaultLayout: true
  pages:
  - name: Basic
    sections:
    - blocks:
      - kind: Block
        name: kubedb.com-v1alpha2-mongodbs
  - name: Operations
    sections:
    - blocks:
      - actions:
          create: Always
        displayMode: List
        kind: Connection
        name: Recent Operations
        query:
          byLabel: ops
          type: GraphQL
        ref:
          group: ops.kubedb.com
          kind: MongoDBOpsRequest
      - actions:
          create: Always
        displayMode: List
        kind: Connection
        name: Recommendations
        query:
          byLabel: recommended_for
          type: GraphQL
        ref:
          group: supervisor.appscode.com
          kind: Recommendation
        view:
          name: supervisor.appscode.com-v1alpha1-recommendations
  - name: Backups
    sections:
    - blocks:
      - kind: Block
        name: kubedb.com-v1alpha2-backups
  - name: Monitoring
    sections:
    - blocks:
      - kind: Block
        name: kubedb.com-v1alpha2-monitoring
  - name: Security
    sections:
    - blocks:
      - kind: Custom
        name: CVE Report
      name: CVE Report
    - blocks:
      - kind: Block
        name: kubedb.com-v1alpha2-rbac
      name: Access Control
    - blocks:
      - kind: Block
        name: kubedb.com-v1alpha2-tls
      name: TLS
    - blocks:
      - kind: Block
        name: kubedb.com-v1alpha2-policies
      name: Policies
  resource:
    group: kubedb.com
    kind: MongoDB
    name: mongodbs
    scope: Namespaced
    version: v1alpha2
