apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: dba.kubedb.com
    k8s.io/kind: PgBouncerModificationRequest
    k8s.io/resource: pgbouncermodificationrequests
    k8s.io/version: v1alpha1
  name: dba.kubedb.com-v1alpha1-pgbouncermodificationrequests
spec:
  resource:
    group: dba.kubedb.com
    kind: PgBouncerModificationRequest
    name: pgbouncermodificationrequests
    scope: Namespaced
    version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PgBouncerModificationRequestSpec is the spec for elasticsearch
            version
          type: object
        status:
          description: PgBouncerModificationRequestStatus is the status for elasticsearch
            version
          properties:
            conditions:
              description: Conditions applied to the request, such as approval or
                denial.
              items:
                properties:
                  lastUpdateTime:
                    description: timestamp for the last update to this condition
                    format: date-time
                    type: string
                  message:
                    description: human readable message with details about the request
                      state
                    type: string
                  reason:
                    description: brief reason for the request state
                    type: string
                  type:
                    description: request approval state, currently Approved or Denied.
                    type: string
                required:
                - type
                type: object
              type: array
          type: object
      type: object
