apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: DatabaseAccessRequest
    k8s.io/resource: databaseaccessrequests
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-databaseaccessrequests
spec:
  resource:
    group: engine.kubevault.com
    kind: DatabaseAccessRequest
    name: databaseaccessrequests
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/engine.kubevault.com/databaseaccessrequests.svg
    type: image/svg+xml