apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: engine.kubevault.com
    k8s.io/kind: GCPRole
    k8s.io/resource: gcproles
    k8s.io/version: v1alpha1
  name: engine.kubevault.com-v1alpha1-gcproles
spec:
  resource:
    group: engine.kubevault.com
    kind: GCPRole
    name: gcproles
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/engine.kubevault.com/gcproles.svg
    type: image/svg+xml