apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: extensions
    k8s.io/kind: DaemonSet
    k8s.io/resource: daemonsets
    k8s.io/version: v1beta1
  name: extensions-v1beta1-daemonsets
spec:
  resource:
    group: extensions
    kind: DaemonSet
    name: daemonsets
    scope: Namespaced
    version: v1beta1
