apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: extensions
    k8s.io/kind: Deployment
    k8s.io/resource: deployments
    k8s.io/version: v1beta1
  name: extensions-v1beta1-deployments
spec:
  resource:
    group: extensions
    kind: Deployment
    name: deployments
    scope: Namespaced
    version: v1beta1
