apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: extensions
    k8s.io/kind: ReplicationControllerDummy
    k8s.io/resource: replicationcontrollers
    k8s.io/version: v1beta1
  name: extensions-v1beta1-replicationcontrollers
spec:
  resource:
    group: extensions
    kind: ReplicationControllerDummy
    name: replicationcontrollers
    scope: Namespaced
    version: v1beta1
