apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceBlockDefinition
metadata:
  creationTimestamp: null
  name: cert-manager.io-v1-certificates
spec:
  blocks:
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: Issuer
    query:
      byLabel: cert_issuer
      type: GraphQL
    ref:
      group: cert-manager.io
      kind: Issuer
  resource:
    group: cert-manager.io
    kind: Certificate
    name: certificates
    scope: Namespaced
    version: v1
