apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: appplatform.azure.upbound.io
    k8s.io/kind: SpringCloudAPIPortalCustomDomain
    k8s.io/resource: springcloudapiportalcustomdomains
    k8s.io/version: v1beta1
  name: appplatform.azure.upbound.io-v1beta1-springcloudapiportalcustomdomains
spec:
  resource:
    group: appplatform.azure.upbound.io
    kind: SpringCloudAPIPortalCustomDomain
    name: springcloudapiportalcustomdomains
    scope: Cluster
    version: v1beta1
