apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ops.kubedb.com
    k8s.io/kind: ElasticsearchOpsRequest
    k8s.io/resource: elasticsearchopsrequests
    k8s.io/version: v1alpha1
  name: ops.kubedb.com-v1alpha1-elasticsearchopsrequests
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/elasticsearchopsrequests.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/ops.kubedb.com/elasticsearchopsrequests.png
    type: image/png
  resource:
    group: ops.kubedb.com
    kind: ElasticsearchOpsRequest
    name: elasticsearchopsrequests
    scope: Namespaced
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  ui:
    editor:
      name: opskubedbcom-elasticsearchopsrequest-editor
      url: https://bundles.byte.builders/ui/
      version: v0.1.0
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            configuration:
              type: object
            databaseRef:
              properties:
                name:
                  type: string
              type: object
            horizontalScaling:
              properties:
                node:
                  format: int32
                  type: integer
                topology:
                  properties:
                    data:
                      format: int32
                      type: integer
                    ingest:
                      format: int32
                      type: integer
                    master:
                      format: int32
                      type: integer
                  type: object
              type: object
            restart:
              type: object
            tls:
              properties:
                certificates:
                  items:
                    properties:
                      alias:
                        type: string
                      dnsNames:
                        items:
                          type: string
                        type: array
                      duration:
                        type: string
                      emailAddresses:
                        items:
                          type: string
                        type: array
                      ipAddresses:
                        items:
                          type: string
                        type: array
                      privateKey:
                        properties:
                          encoding:
                            enum:
                            - PKCS1
                            - PKCS8
                            type: string
                        type: object
                      renewBefore:
                        type: string
                      secretName:
                        type: string
                      subject:
                        properties:
                          countries:
                            items:
                              type: string
                            type: array
                          localities:
                            items:
                              type: string
                            type: array
                          organizationalUnits:
                            items:
                              type: string
                            type: array
                          organizations:
                            items:
                              type: string
                            type: array
                          postalCodes:
                            items:
                              type: string
                            type: array
                          provinces:
                            items:
                              type: string
                            type: array
                          serialNumber:
                            type: string
                          streetAddresses:
                            items:
                              type: string
                            type: array
                        type: object
                      uris:
                        items:
                          type: string
                        type: array
                    required:
                    - alias
                    type: object
                  type: array
                issuerRef:
                  properties:
                    apiGroup:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                  - kind
                  - name
                  type: object
                remove:
                  type: boolean
                rotateCertificates:
                  type: boolean
              type: object
            type:
              enum:
              - Upgrade
              - HorizontalScaling
              - VerticalScaling
              - VolumeExpansion
              - Restart
              - Reconfigure
              - ReconfigureTLS
              type: string
            upgrade:
              properties:
                targetVersion:
                  type: string
              type: object
            verticalScaling:
              properties:
                exporter:
                  properties:
                    limits:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    requests:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                  type: object
                node:
                  properties:
                    limits:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    requests:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                  type: object
                topology:
                  properties:
                    data:
                      properties:
                        limits:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        requests:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                      type: object
                    ingest:
                      properties:
                        limits:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        requests:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                      type: object
                    master:
                      properties:
                        limits:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        requests:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                      type: object
                  type: object
              type: object
            volumeExpansion:
              properties:
                node:
                  anyOf:
                  - type: integer
                  - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                topology:
                  properties:
                    data:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    ingest:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                    master:
                      anyOf:
                      - type: integer
                      - type: string
                      pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                      x-kubernetes-int-or-string: true
                  type: object
              type: object
          required:
          - databaseRef
          - type
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  observedGeneration:
                    format: int64
                    type: integer
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - lastTransitionTime
                - message
                - reason
                - status
                - type
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
            phase:
              enum:
              - Progressing
              - Successful
              - WaitingForApproval
              - Failed
              - Approved
              - Denied
              type: string
          type: object
      type: object
