apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: admissionregistration.k8s.io
    k8s.io/kind: MutatingWebhookConfiguration
    k8s.io/resource: mutatingwebhookconfigurations
    k8s.io/version: v1
  name: admissionregistration.k8s.io-v1-mutatingwebhookconfigurations
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/admissionregistration.k8s.io/mutatingwebhookconfigurations.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/admissionregistration.k8s.io/mutatingwebhookconfigurations.png
    type: image/png
  resource:
    group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: mutatingwebhookconfigurations
    scope: Cluster
    version: v1
