apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: admissionregistration.k8s.io
    k8s.io/kind: ValidatingWebhookConfiguration
    k8s.io/resource: validatingwebhookconfigurations
    k8s.io/version: v1
  name: admissionregistration.k8s.io-v1-validatingwebhookconfigurations
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/admissionregistration.k8s.io/validatingwebhookconfigurations.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/admissionregistration.k8s.io/validatingwebhookconfigurations.png
    type: image/png
  resource:
    group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: validatingwebhookconfigurations
    scope: Cluster
    version: v1
