apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceLayout
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: meta.k8s.appscode.com
    k8s.io/kind: ResourceLayout
    k8s.io/resource: resourcelayouts
    k8s.io/version: v1alpha1
  name: meta.k8s.appscode.com-v1alpha1-resourcelayouts
spec:
  resource:
    group: meta.k8s.appscode.com
    kind: ResourceLayout
    name: resourcelayouts
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: metaappscodecom-resourcedescriptor-editor
      url: https://bundles.byte.builders/ui/
      version: v0.3.0
