apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cluster.open-cluster-management.io
    k8s.io/kind: ManagedCluster
    k8s.io/resource: managedclusters
    k8s.io/version: v1
  name: cluster.open-cluster-management.io-v1-managedclusters
spec:
  columns:
  - format: name
    name: Name
    pathTemplate: '{{ .metadata.name }}'
    priority: 3
    type: string
  - name: Namespace
    pathTemplate: '{{ .metadata.namespace }}'
    priority: 3
    type: string
  - name: Labels
    pathTemplate: '{{ .metadata.labels | toRawJson }}'
    priority: 3
    type: object
  - name: Annotations
    pathTemplate: '{{ .metadata.annotations | toRawJson }}'
    priority: 1
    type: object
  - name: Hub Accepted
    pathTemplate: '{{ get (k8s_convert . ) "Ready" }}'
    priority: 3
    type: string
  - name: Managed Cluster URLs
    pathTemplate: '{{ get (k8s_convert . ) "Status" }}'
    priority: 3
    type: string
  - name: Joined
    pathTemplate: '{{ get (k8s_convert . ) "Restarts" }}'
    priority: 3
    type: integer
  - name: Available
    pathTemplate: '{{ .status.podIP }}'
    priority: 3
    type: string
  - name: Age
    pathTemplate: '{{ .metadata.creationTimestamp }}'
    priority: 3
    sort:
      enable: true
      template: '{{ .metadata.creationTimestamp | toDate "2006-01-02T15:04:05Z07:00" | unixEpoch }}'
      type: integer
    type: date
  defaultView: true
  resource:
    group: cluster.open-cluster-management.io
    kind: ManagedCluster
    name: managedclusters
    scope: Cluster
    version: v1
