apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: voyager.appscode.com
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1beta1
  name: voyager.appscode.com-v1beta1-ingresses
spec:
  resource:
    group: voyager.appscode.com
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1beta1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/voyager.appscode.com/ingress.svg
    type: image/svg+xml
