apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: ConfigMap
    k8s.io/resource: configmaps
    k8s.io/version: v1
  name: core-v1-configmaps
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/configmaps.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/configmaps.png
    type: image/png
  pages:
  - name: Basic
    resources:
    - apiVersion: v1
      kind: Pod
      displayMode: List
      actions:
        create: Never
  resource:
    group: ""
    kind: ConfigMap
    name: configmaps
    scope: Namespaced
    version: v1
  validation:
    openAPIV3Schema:
      description: ConfigMap holds configuration data for pods to consume.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        binaryData:
          additionalProperties:
            format: byte
            type: string
          description: BinaryData contains the binary data. Each key must consist
            of alphanumeric characters, '-', '_' or '.'. BinaryData can contain byte
            sequences that are not in the UTF-8 range. The keys stored in BinaryData
            must not overlap with the ones in the Data field, this is enforced during
            validation process. Using this field will require 1.10+ apiserver and
            kubelet.
          type: object
        data:
          additionalProperties:
            type: string
          description: Data contains the configuration data. Each key must consist
            of alphanumeric characters, '-', '_' or '.'. Values with non-UTF-8 byte
            sequences must use the BinaryData field. The keys stored in Data must
            not overlap with the keys in the BinaryData field, this is enforced during
            validation process.
          type: object
        immutable:
          description: Immutable, if set to true, ensures that data stored in the
            ConfigMap cannot be updated (only object metadata can be modified). If
            not set to true, the field can be modified at any time. Defaulted to nil.
            This is an alpha field enabled by ImmutableEphemeralVolumes feature gate.
          type: boolean
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
          type: object
      type: object
