apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: Namespace
    k8s.io/resource: namespaces
    k8s.io/version: v1
  name: core-v1-namespaces
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/namespaces.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core/namespaces.png
    type: image/png
  resource:
    group: ""
    kind: Namespace
    name: namespaces
    scope: Cluster
    version: v1
  ui:
    editor:
      name: core-namespace-editor
      url: https://bundles.byte.builders/ui/
      version: v0.1.0
  validation:
    openAPIV3Schema:
      description: Namespace provides a scope for Names. Use of multiple namespaces
        is optional.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
          type: object
        spec:
          description: 'Spec defines the behavior of the Namespace. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          properties:
            finalizers:
              description: 'Finalizers is an opaque list of values that must be empty
                to permanently remove object from storage. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/'
              items:
                description: FinalizerName is the name identifying a finalizer during
                  namespace lifecycle.
                type: string
              type: array
          type: object
        status:
          description: 'Status describes the current status of a Namespace. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status'
          properties:
            conditions:
              description: Represents the latest available observations of a namespace's
                current state.
              items:
                description: NamespaceCondition contains details about state of namespace.
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of namespace controller condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            phase:
              description: 'Phase is the current lifecycle phase of the namespace.
                More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/'
              type: string
          type: object
      type: object
