apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: ResourceQuota
    k8s.io/resource: resourcequotas
    k8s.io/version: v1
  name: core-v1-resourcequotas
spec:
  resource:
    group: ""
    kind: ResourceQuota
    name: resourcequotas
    scope: Namespaced
    version: v1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/quota.svg
    type: image/svg+xml