apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: Secret
    k8s.io/resource: secrets
    k8s.io/version: v1
  name: core-v1-secrets
spec:
  resource:
    group: ""
    kind: Secret
    name: secrets
    scope: Namespaced
    version: v1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/secret.svg
    type: image/svg+xml
  columns:
    - jsonPath: .metadata.name
      name: Name
      type: string
      priority: 3
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
      priority: 3
    - jsonPath: .metadata.labels
      name: Labels
      type: object
      priority: 3
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
      priority: 3
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
      priority: 3
    - jsonPath: .kind
      name: Kind
      type: string
      priority: 3
  keyTargets:
    - apiVersion: v1
      kind: Pod
  validation:
    openAPIV3Schema:
      description: Secret holds secret data of a certain type. The total bytes of
        the values in the Data field must be less than MaxSecretSize bytes.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        data:
          additionalProperties:
            format: byte
            type: string
          description: Data contains the secret data. Each key must consist of alphanumeric
            characters, '-', '_' or '.'. The serialized form of the secret data is
            a base64 encoded string, representing the arbitrary (possibly non-string)
            data value here. Described in https://tools.ietf.org/html/rfc4648#section-4
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: 'Standard object''s metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata'
          type: object
        stringData:
          additionalProperties:
            type: string
          description: stringData allows specifying non-binary secret data in string
            form. It is provided as a write-only convenience method. All keys and
            values are merged into the data field on write, overwriting any existing
            values. It is never output when reading from the API.
          type: object
        type:
          description: Used to facilitate programmatic handling of secret data.
          type: string
      type: object
