apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: Service
    k8s.io/resource: services
    k8s.io/version: v1
  name: core-v1-services
spec:
  resource:
    group: ""
    kind: Service
    name: services
    scope: Namespaced
    version: v1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core/svc.svg
    type: image/svg+xml
  keyTargets:
    - apiVersion: v1
      kind: Pod
  connections:
    - target:
        apiVersion: v1
        kind: Pod
      type: MatchSelector
      namespacePath: "metadata.namespace"
      selectorPath: "spec.selector"
    - target:
        apiVersion: apps/v1
        kind: Deployment
      type: MatchSelector
      namespacePath: "metadata.namespace"
      selectorPath: "spec.selector"
      targetLabelPath: "spec.template.metadata.labels"
