apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: policy.kubevault.com
    k8s.io/kind: VaultPolicyBinding
    k8s.io/resource: vaultpolicybindings
    k8s.io/version: v1alpha1
  name: policy.kubevault.com-v1alpha1-vaultpolicybindings
spec:
  resource:
    group: policy.kubevault.com
    kind: VaultPolicyBinding
    name: vaultpolicybindings
    scope: Namespaced
    version: v1alpha1
