apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: policy.kubevault.com
    k8s.io/kind: VaultPolicy
    k8s.io/resource: vaultpolicies
    k8s.io/version: v1alpha1
  name: policy.kubevault.com-v1alpha1-vaultpolicies
spec:
  resource:
    group: policy.kubevault.com
    kind: VaultPolicy
    name: vaultpolicies
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/policy.kubevault.com/vaultpolicies.svg
    type: image/svg+xml
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: 'More info: https://www.vaultproject.io/docs/concepts/policies.html'
          properties:
            policy:
              description: Policy specifies a vault policy in json format.
              type: object
              x-kubernetes-embedded-resource: true
              x-kubernetes-preserve-unknown-fields: true
            policyDocument:
              description: 'PolicyDocument specifies a vault policy in hcl format.
                For example: path "secret/*" {   capabilities = ["create", "read",
                "update", "delete", "list"] }'
              type: string
            vaultPolicyName:
              description: 'VaultPolicyName is the policy name set inside Vault. This
                defaults to following format: k8s.${cluster}.${metadata.namespace}.${metadata.name}'
              type: string
            vaultRef:
              description: VaultRef is the name of a AppBinding referencing to a Vault
                Server
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
          required:
          - vaultRef
          type: object
        status:
          properties:
            conditions:
              description: Represents the latest available observations of a VaultPolicy.
              items:
                description: PolicyCondition describes the state of a VaultPolicy
                  at a certain point.
                properties:
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  reason:
                    description: The reason for the condition's.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: Type of PolicyCondition condition.
                    type: string
                type: object
              type: array
            observedGeneration:
              description: ObservedGeneration is the most recent generation observed
                for this resource. It corresponds to the resource's generation, which
                is updated on mutation by the API Server.
              format: int64
              type: integer
            phase:
              description: Phase indicates whether the policy successfully applied
                in vault or not or in progress
              type: string
          type: object
      type: object
