apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: policy.kubevault.com
    k8s.io/kind: VaultPolicy
    k8s.io/resource: vaultpolicies
    k8s.io/version: v1alpha1
  name: policy.kubevault.com-v1alpha1-vaultpolicies
spec:
  resource:
    group: policy.kubevault.com
    kind: VaultPolicy
    name: vaultpolicies
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/policy.kubevault.com/vaultpolicies.svg
    type: image/svg+xml