apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: policy
    k8s.io/kind: PodDisruptionBudget
    k8s.io/resource: poddisruptionbudgets
    k8s.io/version: v1beta1
  name: policy-v1beta1-poddisruptionbudgets
spec:
  resource:
    group: policy
    kind: PodDisruptionBudget
    name: poddisruptionbudgets
    scope: Namespaced
    version: v1beta1
  columns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
