apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: policy
    k8s.io/kind: PodSecurityPolicy
    k8s.io/resource: podsecuritypolicies
    k8s.io/version: v1beta1
  name: policy-v1beta1-podsecuritypolicies
spec:
  resource:
    group: policy
    kind: PodSecurityPolicy
    name: podsecuritypolicies
    scope: Cluster
    version: v1beta1
