apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: rbac.authorization.k8s.io
    k8s.io/kind: ClusterRole
    k8s.io/resource: clusterroles
    k8s.io/version: v1
  name: rbac.authorization.k8s.io-v1-clusterroles
spec:
  resource:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: clusterroles
    scope: Cluster
    version: v1
  columns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
  keyTargets:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
