apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: rbac.authorization.k8s.io
    k8s.io/kind: ClusterRoleBinding
    k8s.io/resource: clusterrolebindings
    k8s.io/version: v1
  name: rbac.authorization.k8s.io-v1-clusterrolebindings
spec:
  resource:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: clusterrolebindings
    scope: Cluster
    version: v1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/rbac.authorization.k8s.io/crb.svg
    type: image/svg+xml