apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: rbac.authorization.k8s.io
    k8s.io/kind: Role
    k8s.io/resource: roles
    k8s.io/version: v1
  name: rbac.authorization.k8s.io-v1-roles
spec:
  resource:
    group: rbac.authorization.k8s.io
    kind: Role
    name: roles
    scope: Namespaced
    version: v1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/rbac.authorization.k8s.io/role.svg
    type: image/svg+xml
  keyTargets:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
