apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: certificates.k8s.io
    k8s.io/kind: CertificateSigningRequest
    k8s.io/resource: certificatesigningrequests
    k8s.io/version: v1beta1
  name: certificates.k8s.io-v1beta1-certificatesigningrequests
spec:
  resource:
    group: certificates.k8s.io
    kind: CertificateSigningRequest
    name: certificatesigningrequests
    scope: Cluster
    version: v1beta1
  displayColumns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
