apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ui.k8s.appscode.com
    k8s.io/kind: GenericResourceService
    k8s.io/resource: genericresourceservices
    k8s.io/version: v1alpha1
  name: ui.k8s.appscode.com-v1alpha1-genericresourceservices
spec:
  columns:
  - name: Group
    pathTemplate: '{{ .spec.apiType.group }}'
    priority: 3
    type: string
  - name: Version
    pathTemplate: '{{ .spec.apiType.version }}'
    priority: 3
    type: string
  - name: Name
    pathTemplate: '{{ .spec.apiType.name }}'
    priority: 3
    type: string
  - name: Kind
    pathTemplate: '{{ .spec.apiType.kind }}'
    priority: 3
    type: string
  - name: Scope
    pathTemplate: '{{ .spec.apiType.scope }}'
    priority: 3
    type: string
  - name: Exposed
    pathTemplate: '{{ .spec.facilities.exposed.usage }}'
    priority: 3
    type: string
  - name: TLS
    pathTemplate: '{{ .spec.facilities.tls.usage }}'
    priority: 3
    type: string
  - name: Backup
    pathTemplate: '{{ .spec.facilities.backup.usage }}'
    priority: 3
    type: string
  - name: Monitoring
    pathTemplate: '{{ .spec.facilities.monitoring.usage }}'
    priority: 3
    type: string
  - name: Status
    pathTemplate: '{{ .status.phase }}'
    priority: 3
    type: string
  defaultView: true
  resource:
    group: ui.k8s.appscode.com
    kind: GenericResourceService
    name: genericresourceservices
    scope: Namespaced
    version: v1alpha1
