apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: BackupConfiguration
    k8s.io/resource: backupconfigurations
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-backupconfigurations
spec:
  resource:
    group: stash.appscode.com
    kind: BackupConfiguration
    name: backupconfigurations
    scope: Namespaced
    version: v1beta1
