apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: BackupBatch
    k8s.io/resource: backupbatches
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-backupbatches
spec:
  resource:
    group: stash.appscode.com
    kind: BackupBatch
    name: backupbatches
    scope: Namespaced
    version: v1beta1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/backupbatches.svg
    type: image/svg+xml