apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: Function
    k8s.io/resource: functions
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-functions
spec:
  resource:
    group: stash.appscode.com
    kind: Function
    name: functions
    scope: Cluster
    version: v1beta1
