apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: RestoreSession
    k8s.io/resource: restoresessions
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-restoresessions
spec:
  resource:
    group: stash.appscode.com
    kind: RestoreSession
    name: restoresessions
    scope: Namespaced
    version: v1beta1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/restoresessions.svg
    type: image/svg+xml