apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: Task
    k8s.io/resource: tasks
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-tasks
spec:
  resource:
    group: stash.appscode.com
    kind: Task
    name: tasks
    scope: Cluster
    version: v1beta1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/tasks.svg
    type: image/svg+xml