apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: streamanalytics.azure.upbound.io
    k8s.io/kind: OutputBlob
    k8s.io/resource: outputblobs
    k8s.io/version: v1beta1
  name: streamanalytics.azure.upbound.io-v1beta1-outputblobs
spec:
  resource:
    group: streamanalytics.azure.upbound.io
    kind: OutputBlob
    name: outputblobs
    scope: Cluster
    version: v1beta1
