apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cert-manager.io
    k8s.io/kind: Certificate
    k8s.io/resource: certificates
    k8s.io/version: v1alpha2
  name: cert-manager.io-v1alpha2-certificates
spec:
  resource:
    group: cert-manager.io
    kind: Certificate
    name: certificates
    scope: Namespaced
    version: v1alpha2
  icons:
  - src: https://cdn.appscode.com/k8s/icons/cert-manager.io/certificates.svg
    type: image/svg+xml