apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cert-manager.io
    k8s.io/kind: CertificateRequest
    k8s.io/resource: certificaterequests
    k8s.io/version: v1alpha2
  name: cert-manager.io-v1alpha2-certificaterequests
spec:
  resource:
    group: cert-manager.io
    kind: CertificateRequest
    name: certificaterequests
    scope: Namespaced
    version: v1alpha2
  icons:
  - src: https://cdn.appscode.com/k8s/icons/cert-manager.io/certificaterequests.svg
    type: image/svg+xml