apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cert-manager.io
    k8s.io/kind: Issuer
    k8s.io/resource: issuers
    k8s.io/version: v1alpha2
  name: cert-manager.io-v1alpha2-issuers
spec:
  resource:
    group: cert-manager.io
    kind: Issuer
    name: issuers
    scope: Namespaced
    version: v1alpha2
  icons:
  - src: https://cdn.appscode.com/k8s/icons/cert-manager.io/issuers.svg
    type: image/svg+xml