apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: authorization.k8s.io
    k8s.io/kind: SelfSubjectRulesReview
    k8s.io/resource: selfsubjectrulesreviews
    k8s.io/version: v1beta1
  name: authorization.k8s.io-v1beta1-selfsubjectrulesreviews
spec:
  resource:
    group: authorization.k8s.io
    kind: SelfSubjectRulesReview
    name: selfsubjectrulesreviews
    scope: Cluster
    version: v1beta1
