apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubevault.com
    k8s.io/kind: VaultServerVersion
    k8s.io/resource: vaultserverversions
    k8s.io/version: v1alpha1
  name: catalog.kubevault.com-v1alpha1-vaultserverversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubevault.com/vaultserverversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubevault.com/vaultserverversions.png
    type: image/png
  resource:
    group: catalog.kubevault.com
    kind: VaultServerVersion
    name: vaultserverversions
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: catalogkubevaultcom-vaultserverversion-editor
      url: https://bundles.byte.builders/ui/
      version: v0.1.0
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VaultServerVersionSpec is the spec for postgres version
          properties:
            deprecated:
              description: Deprecated versions usable but regarded as obsolete and
                best avoided, typically due to having been superseded.
              type: boolean
            exporter:
              description: Exporter Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            unsealer:
              description: Unsealer Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            vault:
              description: Vault Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              description: Version
              type: string
          required:
          - exporter
          - unsealer
          - vault
          - version
          type: object
      type: object
