apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling
    k8s.io/kind: HorizontalPodAutoscaler
    k8s.io/resource: horizontalpodautoscalers
    k8s.io/version: v2beta1
  name: autoscaling-v2beta1-horizontalpodautoscalers
spec:
  resource:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    name: horizontalpodautoscalers
    scope: Namespaced
    version: v2beta1
