apiVersion: meta.k8s.appscode.com/v1alpha1
kind: MenuOutline
metadata:
  creationTimestamp: null
  name: ocm-hub
spec:
  sections:
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/workloads.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/workloads.png
      type: image/png
    items:
    - name: Managed Clusters
      required: true
      type:
        group: cluster.open-cluster-management.io
        kind: ManagedCluster
    name: Clusters
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/helm.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/helm.png
      type: image/png
    items:
    - name: Managed Cluster Sets
      type:
        group: cluster.open-cluster-management.io
        kind: ManagedClusterSet
    - name: Managed ClusterSet Bindings
      type:
        group: cluster.open-cluster-management.io
        kind: ManagedClusterSetBinding
    name: Cluster Sets
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/networking.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/networking.png
      type: image/png
    items:
    - name: Managed Cluster Addons
      required: true
      type:
        group: addon.open-cluster-management.io
        kind: ManagedClusterAddOn
    - name: Cluster Management AddOns
      required: true
      type:
        group: addon.open-cluster-management.io
        kind: ClusterManagementAddOn
    - name: AddOn Deployment Config
      required: true
      type:
        group: addon.open-cluster-management.io
        kind: AddOnDeploymentConfig
    - name: AddOn Templates
      required: true
      type:
        group: addon.open-cluster-management.io
        kind: AddOnTemplate
    name: AddOns
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/config.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/config.png
      type: image/png
    items:
    - name: ManifestWork ReplicaSets
      required: true
      type:
        group: work.open-cluster-management.io
        kind: ManifestWorkReplicaSet
    - name: ManifestWorks
      required: true
      type:
        group: work.open-cluster-management.io
        kind: ManifestWork
    - name: Placements
      required: true
      type:
        group: cluster.open-cluster-management.io
        kind: Placement
    - name: Placement Decisions
      required: true
      type:
        group: cluster.open-cluster-management.io
        kind: PlacementDecision
    name: ManifestWork & Placements
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/admin.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/admin.png
      type: image/png
    items:
    - name: Managed Service Accounts
      required: true
      type:
        group: authentication.open-cluster-management.io
        kind: ManagedServiceAccount
    - name: Cluster Gateways
      required: true
      type:
        group: gateway.open-cluster-management.io
        kind: ClusterGateway
    - name: Managed Proxy Service Resolvers
      type:
        group: proxy.open-cluster-management.io
        kind: ManagedProxyServiceResolver
    - name: Managed Proxy Configurations
      type:
        group: proxy.open-cluster-management.io
        kind: ManagedProxyConfiguration
    - name: Cluster Gateway Configurations
      required: true
      type:
        group: config.gateway.open-cluster-management.io
        kind: ClusterGatewayConfiguration
    name: OCM Core AddOns Config
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/helm.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/helm.png
      type: image/png
    items:
    - name: User Access Settings
      path: /settings/access
    name: Access
  - icons:
    - src: https://cdn.appscode.com/k8s/icons/menu/helm.svg
      type: image/svg+xml
    - src: https://cdn.appscode.com/k8s/icons/menu/helm.png
      type: image/png
    items:
    - name: License Settings
      path: /settings/license
    name: License
