apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: ElasticsearchAutoscaler
    k8s.io/resource: elasticsearchautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-elasticsearchautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: ElasticsearchAutoscaler
    name: elasticsearchautoscalers
    scope: Namespaced
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            compute:
              properties:
                disableScaleDown:
                  type: boolean
                node:
                  properties:
                    containerControlledValues:
                      type: string
                    controlledResources:
                      items:
                        type: string
                      type: array
                    inMemoryScalingThreshold:
                      format: int32
                      type: integer
                    maxAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    minAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    podLifeTimeThreshold:
                      type: string
                    resourceDiffPercentage:
                      format: int32
                      type: integer
                    trigger:
                      type: string
                  type: object
                topology:
                  properties:
                    data:
                      properties:
                        containerControlledValues:
                          type: string
                        controlledResources:
                          items:
                            type: string
                          type: array
                        inMemoryScalingThreshold:
                          format: int32
                          type: integer
                        maxAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        minAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        podLifeTimeThreshold:
                          type: string
                        resourceDiffPercentage:
                          format: int32
                          type: integer
                        trigger:
                          type: string
                      type: object
                    ingest:
                      properties:
                        containerControlledValues:
                          type: string
                        controlledResources:
                          items:
                            type: string
                          type: array
                        inMemoryScalingThreshold:
                          format: int32
                          type: integer
                        maxAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        minAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        podLifeTimeThreshold:
                          type: string
                        resourceDiffPercentage:
                          format: int32
                          type: integer
                        trigger:
                          type: string
                      type: object
                    master:
                      properties:
                        containerControlledValues:
                          type: string
                        controlledResources:
                          items:
                            type: string
                          type: array
                        inMemoryScalingThreshold:
                          format: int32
                          type: integer
                        maxAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        minAllowed:
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                            x-kubernetes-int-or-string: true
                          type: object
                        podLifeTimeThreshold:
                          type: string
                        resourceDiffPercentage:
                          format: int32
                          type: integer
                        trigger:
                          type: string
                      type: object
                  type: object
              type: object
            databaseRef:
              properties:
                name:
                  type: string
              type: object
            storage:
              properties:
                node:
                  properties:
                    scalingThreshold:
                      format: int32
                      type: integer
                    trigger:
                      type: string
                    usageThreshold:
                      format: int32
                      type: integer
                  type: object
                topology:
                  properties:
                    data:
                      properties:
                        scalingThreshold:
                          format: int32
                          type: integer
                        trigger:
                          type: string
                        usageThreshold:
                          format: int32
                          type: integer
                      type: object
                    ingest:
                      properties:
                        scalingThreshold:
                          format: int32
                          type: integer
                        trigger:
                          type: string
                        usageThreshold:
                          format: int32
                          type: integer
                      type: object
                    master:
                      properties:
                        scalingThreshold:
                          format: int32
                          type: integer
                        trigger:
                          type: string
                        usageThreshold:
                          format: int32
                          type: integer
                      type: object
                  type: object
              type: object
          required:
          - databaseRef
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  observedGeneration:
                    format: int64
                    type: integer
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - lastTransitionTime
                - message
                - reason
                - status
                - type
                type: object
              type: array
            observedGeneration:
              format: int64
              type: integer
          type: object
      type: object
