apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: autoscaling.kubedb.com
    k8s.io/kind: VerticalAutoscaler
    k8s.io/resource: verticalautoscalers
    k8s.io/version: v1alpha1
  name: autoscaling.kubedb.com-v1alpha1-verticalautoscalers
spec:
  resource:
    group: autoscaling.kubedb.com
    kind: VerticalAutoscaler
    name: verticalautoscalers
    scope: Namespaced
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            configServer:
              properties:
                compute:
                  properties:
                    containerControlledValues:
                      type: string
                    controlledResources:
                      items:
                        type: string
                      type: array
                    disable:
                      type: boolean
                    maxAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    minAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    podLifeTimeThreshold:
                      format: int64
                      type: integer
                    resourceDiffPercentage:
                      format: int32
                      type: integer
                  type: object
                storage:
                  properties:
                    scalingThreshold:
                      type: integer
                    usageThreshold:
                      type: integer
                  type: object
              type: object
            databaseRef:
              properties:
                apiGroup:
                  type: string
                kind:
                  type: string
                name:
                  type: string
              required:
              - kind
              - name
              type: object
            mongos:
              properties:
                compute:
                  properties:
                    containerControlledValues:
                      type: string
                    controlledResources:
                      items:
                        type: string
                      type: array
                    disable:
                      type: boolean
                    maxAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    minAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    podLifeTimeThreshold:
                      format: int64
                      type: integer
                    resourceDiffPercentage:
                      format: int32
                      type: integer
                  type: object
                storage:
                  properties:
                    scalingThreshold:
                      type: integer
                    usageThreshold:
                      type: integer
                  type: object
              type: object
            replicaSet:
              properties:
                compute:
                  properties:
                    containerControlledValues:
                      type: string
                    controlledResources:
                      items:
                        type: string
                      type: array
                    disable:
                      type: boolean
                    maxAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    minAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    podLifeTimeThreshold:
                      format: int64
                      type: integer
                    resourceDiffPercentage:
                      format: int32
                      type: integer
                  type: object
                storage:
                  properties:
                    scalingThreshold:
                      type: integer
                    usageThreshold:
                      type: integer
                  type: object
              type: object
            shard:
              properties:
                compute:
                  properties:
                    containerControlledValues:
                      type: string
                    controlledResources:
                      items:
                        type: string
                      type: array
                    disable:
                      type: boolean
                    maxAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    minAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    podLifeTimeThreshold:
                      format: int64
                      type: integer
                    resourceDiffPercentage:
                      format: int32
                      type: integer
                  type: object
                storage:
                  properties:
                    scalingThreshold:
                      type: integer
                    usageThreshold:
                      type: integer
                  type: object
              type: object
            standalone:
              properties:
                compute:
                  properties:
                    containerControlledValues:
                      type: string
                    controlledResources:
                      items:
                        type: string
                      type: array
                    disable:
                      type: boolean
                    maxAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    minAllowed:
                      additionalProperties:
                        anyOf:
                        - type: integer
                        - type: string
                        pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        x-kubernetes-int-or-string: true
                      type: object
                    podLifeTimeThreshold:
                      format: int64
                      type: integer
                    resourceDiffPercentage:
                      format: int32
                      type: integer
                  type: object
                storage:
                  properties:
                    scalingThreshold:
                      type: integer
                    usageThreshold:
                      type: integer
                  type: object
              type: object
          required:
          - databaseRef
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  observedGeneration:
                    format: int64
                    type: integer
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - lastTransitionTime
                - message
                - reason
                - status
                - type
                type: object
              type: array
          type: object
      required:
      - spec
      type: object
