apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: rbac.authorization.k8s.io
    k8s.io/kind: RoleBinding
    k8s.io/resource: rolebindings
    k8s.io/version: v1beta1
  name: rbac.authorization.k8s.io-v1beta1-rolebindings
spec:
  resource:
    group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rolebindings
    scope: Namespaced
    version: v1beta1
