apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: ComponentStatus
    k8s.io/resource: componentstatuses
    k8s.io/version: v1
  name: core-v1-componentstatuses
spec:
  resource:
    group: ""
    kind: ComponentStatus
    name: componentstatuses
    scope: Cluster
    version: v1
  columns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
