apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ""
    k8s.io/kind: Secret
    k8s.io/resource: secrets
    k8s.io/version: v1
  name: core-v1-secrets
spec:
  resource:
    group: ""
    kind: Secret
    name: secrets
    scope: Namespaced
    version: v1
  columns:
    - jsonPath: .metadata.name
      name: Name
      type: string
      priority: 3
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
      priority: 3
    - jsonPath: .metadata.labels
      name: Labels
      type: object
      priority: 3
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
      priority: 3
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
      priority: 3
    - jsonPath: .kind
      name: Kind
      type: string
      priority: 3
  keyTargets:
    - apiVersion: v1
      kind: Pod
