apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: grafana.searchlight.dev
    k8s.io/kind: Datasource
    k8s.io/resource: datasources
    k8s.io/version: v1alpha1
  name: grafana.searchlight.dev-v1alpha1-datasources
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/grafana.searchlight.dev/datasources.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/grafana.searchlight.dev/datasources.png
    type: image/png
  resource:
    group: grafana.searchlight.dev
    kind: Datasource
    name: datasources
    scope: Namespaced
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  ui:
    editor:
      name: grafanasearchlightdev-datasource-editor
      url: https://bundles.byte.builders/ui/
      version: v0.1.0
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          properties:
            observedGeneration:
              description: ObservedGeneration is the most recent generation observed for this resource. It corresponds to the resource's generation, which is updated on mutation by the API Server.
              format: int64
              type: integer
          type: object
      type: object
