apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: datalossprevention.gcp.upbound.io
    k8s.io/kind: InspectTemplate
    k8s.io/resource: inspecttemplates
    k8s.io/version: v1beta1
  name: datalossprevention.gcp.upbound.io-v1beta1-inspecttemplates
spec:
  resource:
    group: datalossprevention.gcp.upbound.io
    kind: InspectTemplate
    name: inspecttemplates
    scope: Cluster
    version: v1beta1
