apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Elasticsearch
    k8s.io/resource: elasticsearches
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-elasticsearches
spec:
  resource:
    group: kubedb.com
    kind: Elasticsearch
    name: elasticsearches
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/elasticsearch.svg
    type: image/svg+xml
