apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Etcd
    k8s.io/resource: etcds
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-etcds
spec:
  resource:
    group: kubedb.com
    kind: Etcd
    name: etcds
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/etcd.svg
    type: image/svg+xml