apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: MariaDB
    k8s.io/resource: mariadbs
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-mariadbs
spec:
  resource:
    group: kubedb.com
    kind: MariaDB
    name: mariadbs
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mariadbs.svg
    type: image/svg+xml