apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Memcached
    k8s.io/resource: memcacheds
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-memcacheds
spec:
  resource:
    group: kubedb.com
    kind: Memcached
    name: memcacheds
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/memcached.svg
    type: image/svg+xml
