apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: MySQL
    k8s.io/resource: mysqls
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-mysqls
spec:
  resource:
    group: kubedb.com
    kind: MySQL
    name: mysqls
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/mysql.svg
    type: image/svg+xml
