apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: PgBouncer
    k8s.io/resource: pgbouncers
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-pgbouncers
spec:
  resource:
    group: kubedb.com
    kind: PgBouncer
    name: pgbouncers
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/pgbouncer.svg
    type: image/svg+xml