apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Redis
    k8s.io/resource: redises
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-redises
spec:
  resource:
    group: kubedb.com
    kind: Redis
    name: redises
    scope: Namespaced
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/kubedb.com/redis.svg
    type: image/svg+xml
