apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Snapshot
    k8s.io/resource: snapshots
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-snapshots
spec:
  resource:
    group: kubedb.com
    kind: Snapshot
    name: snapshots
    scope: Namespaced
    version: v1alpha1
