apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: Postgres
    k8s.io/resource: postgreses
    k8s.io/version: v1alpha1
  name: kubedb.com-v1alpha1-postgreses
spec:
  resource:
    group: kubedb.com
    kind: Postgres
    name: postgreses
    scope: Namespaced
    version: v1alpha1
  displayColumns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
  connections:
    - target:
        apiVersion: apps/v1
        kind: StatefulSet
      type: MatchName
      namespacePath: "metadata.namespace"
      nameTemplate: "{.metadata.name}"
      level: Owner
    - target:
        apiVersion: v1
        kind: Service
      type: MatchSelector
      namespacePath: "metadata.namespace"
      selector:
        matchLabels:
          kubedb.com/kind: Postgres
          kubedb.com/name: "{.metadata.name}"
      level: Owner
    - target:
        apiVersion: appcatalog.appscode.com/v1alpha1
        kind: AppBinding
      type: MatchName
      namespacePath: "metadata.namespace"
      nameTemplate: "{.metadata.name}"
      level: Owner
