apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: ElasticsearchVersion
    k8s.io/resource: elasticsearchversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-elasticsearchversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/elasticsearchversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/elasticsearchversions.png
    type: image/png
  resource:
    group: catalog.kubedb.com
    kind: ElasticsearchVersion
    name: elasticsearchversions
    scope: Cluster
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            authPlugin:
              enum:
              - SearchGuard
              - X-Pack
              - OpenDistro
              type: string
            db:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            deprecated:
              type: boolean
            exporter:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            initContainer:
              properties:
                image:
                  type: string
                yqImage:
                  type: string
              required:
              - image
              - yqImage
              type: object
            podSecurityPolicies:
              properties:
                databasePolicyName:
                  type: string
              required:
              - databasePolicyName
              type: object
            tools:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              type: string
          required:
          - authPlugin
          - db
          - exporter
          - initContainer
          - podSecurityPolicies
          - version
          type: object
      type: object
