apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: EtcdVersion
    k8s.io/resource: etcdversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-etcdversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/etcdversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/etcdversions.png
    type: image/png
  resource:
    group: catalog.kubedb.com
    kind: EtcdVersion
    name: etcdversions
    scope: Cluster
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  ui:
    editor:
      name: catalogkubedbcom-etcdversion-editor
      url: https://bundles.byte.builders/ui/
      version: v0.1.0
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            db:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            deprecated:
              type: boolean
            exporter:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            tools:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              type: string
          required:
          - db
          - exporter
          - tools
          - version
          type: object
      type: object
