apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: MongoDBVersion
    k8s.io/resource: mongodbversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-mongodbversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/mongodbversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/mongodbversions.png
    type: image/png
  resource:
    group: catalog.kubedb.com
    kind: MongoDBVersion
    name: mongodbversions
    scope: Cluster
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  ui:
    editor:
      name: catalogkubedbcom-mongodbversion-editor
      url: https://bundles.byte.builders/ui/
      version: v0.1.0
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          properties:
            annotations:
              additionalProperties:
                type: string
              description: 'Annotations is an unstructured key value map stored with
                a resource that may be set by external tools to store and retrieve
                arbitrary metadata. They are not queryable and should be preserved
                when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
              type: object
            labels:
              additionalProperties:
                type: string
              description: 'Map of string keys and values that can be used to organize
                and categorize (scope and select) objects. May match selectors of
                replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
              type: object
            name:
              description: 'Name must be unique within a namespace. Is required when
                creating resources, although some resources may allow a client to
                request the generation of an appropriate name automatically. Name
                is primarily intended for creation idempotence and configuration definition.
                Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
              type: string
            namespace:
              description: "Namespace defines the space within which each name must
                be unique. An empty namespace is equivalent to the \"default\" namespace,
                but \"default\" is the canonical representation. Not all objects are
                required to be scoped to a namespace - the value of this field for
                those objects will be empty. \n Must be a DNS_LABEL. Cannot be updated.
                More info: http://kubernetes.io/docs/user-guide/namespaces"
              type: string
          type: object
        spec:
          properties:
            db:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            deprecated:
              type: boolean
            exporter:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            initContainer:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            podSecurityPolicies:
              properties:
                databasePolicyName:
                  type: string
              required:
              - databasePolicyName
              type: object
            replicationModeDetector:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            stash:
              properties:
                addon:
                  properties:
                    backupTask:
                      properties:
                        name:
                          type: string
                        params:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            required:
                            - name
                            - value
                            type: object
                          type: array
                      required:
                      - name
                      type: object
                    restoreTask:
                      properties:
                        name:
                          type: string
                        params:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            required:
                            - name
                            - value
                            type: object
                          type: array
                      required:
                      - name
                      type: object
                  required:
                  - backupTask
                  - restoreTask
                  type: object
              type: object
            tools:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              type: string
          required:
          - db
          - exporter
          - initContainer
          - podSecurityPolicies
          - replicationModeDetector
          - tools
          - version
          type: object
      type: object
