apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: MySQLVersion
    k8s.io/resource: mysqlversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-mysqlversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: MySQLVersion
    name: mysqlversions
    scope: Cluster
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/mysqlversions.svg
    type: image/svg+xml
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            db:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            deprecated:
              type: boolean
            exporter:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            initContainer:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            podSecurityPolicies:
              properties:
                databasePolicyName:
                  type: string
                snapshotterPolicyName:
                  type: string
              required:
              - databasePolicyName
              - snapshotterPolicyName
              type: object
            tools:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              type: string
          required:
          - db
          - exporter
          - initContainer
          - podSecurityPolicies
          - tools
          - version
          type: object
      type: object
