apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: MySQLVersion
    k8s.io/resource: mysqlversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-mysqlversions
spec:
  resource:
    group: catalog.kubedb.com
    kind: MySQLVersion
    name: mysqlversions
    scope: Cluster
    version: v1alpha1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/mysqlversions.svg
    type: image/svg+xml
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MySQLVersionSpec is the spec for postgres version
          properties:
            db:
              description: Database Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            deprecated:
              description: Deprecated versions usable but regarded as obsolete and
                best avoided, typically due to having been superseded.
              type: boolean
            exporter:
              description: Exporter Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            initContainer:
              description: Init container Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            podSecurityPolicies:
              description: PSP names
              properties:
                databasePolicyName:
                  type: string
              required:
              - databasePolicyName
              type: object
            replicationModeDetector:
              description: ReplicationModeDetector Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            tools:
              description: Tools Image
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              description: Version
              type: string
          required:
          - db
          - exporter
          - initContainer
          - podSecurityPolicies
          - replicationModeDetector
          - tools
          - version
          type: object
      type: object
