apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: PgBouncerVersion
    k8s.io/resource: pgbouncerversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-pgbouncerversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/pgbouncerversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/pgbouncerversions.png
    type: image/png
  resource:
    group: catalog.kubedb.com
    kind: PgBouncerVersion
    name: pgbouncerversions
    scope: Cluster
    version: v1alpha1
  resourceRequirements:
  - resources: spec.podTemplate.spec.resources
    units: spec.replicas
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deprecated:
              type: boolean
            exporter:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            server:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              type: string
          required:
          - exporter
          - server
          - version
          type: object
      type: object
