apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: catalog.kubedb.com
    k8s.io/kind: ProxySQLVersion
    k8s.io/resource: proxysqlversions
    k8s.io/version: v1alpha1
  name: catalog.kubedb.com-v1alpha1-proxysqlversions
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/proxysqlversions.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/catalog.kubedb.com/proxysqlversions.png
    type: image/png
  resource:
    group: catalog.kubedb.com
    kind: ProxySQLVersion
    name: proxysqlversions
    scope: Cluster
    version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deprecated:
              type: boolean
            exporter:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            podSecurityPolicies:
              properties:
                databasePolicyName:
                  type: string
              required:
              - databasePolicyName
              type: object
            proxysql:
              properties:
                image:
                  type: string
              required:
              - image
              type: object
            version:
              type: string
          required:
          - exporter
          - podSecurityPolicies
          - proxysql
          - version
          type: object
      type: object
