apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: batch
    k8s.io/kind: CronJob
    k8s.io/resource: cronjobs
    k8s.io/version: v1beta1
  name: batch-v1beta1-cronjobs
spec:
  resource:
    group: batch
    kind: CronJob
    name: cronjobs
    scope: Namespaced
    version: v1beta1
  icons:
  - src: https://cdn.appscode.com/k8s/icons/batch/cronjob.svg
    type: image/svg+xml
  columns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .spec.schedule
      name: Schedule
      type: string
    - jsonPath: '{range .spec.jobTemplate.spec.template.spec.containers[*]}{.image}{"\n"}{end}'
      name: Images
      type: string
      format: csv
  keyTargets:
    - apiVersion: v1
      kind: Pod
    - apiVersion: v1
      kind: Service
