apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceClass
metadata:
  creationTimestamp: null
  name: Admin
  namespace: cluster
spec:
  entries:
  - layoutName: ""
    name: Namespaces
    required: true
    type:
      group: ""
      kind: Namespace
  - layoutName: ""
    name: Limit Ranges
    type:
      group: ""
      kind: LimitRange
  - layoutName: ""
    name: Resource Quotas
    type:
      group: ""
      kind: ResourceQuota
  - layoutName: ""
    name: Cluster Roles
    required: true
    type:
      group: rbac.authorization.k8s.io
      kind: ClusterRole
  - layoutName: ""
    name: Roles
    required: true
    type:
      group: rbac.authorization.k8s.io
      kind: Role
  - layoutName: ""
    name: CSI Drivers
    type:
      group: storage.k8s.io
      kind: CSIDriver
  icons:
  - src: https://cdn.appscode.com/k8s/icons/resourceclasses/admin.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/resourceclasses/admin.png
    type: image/png
  weight: 10
