apiVersion: meta.appscode.com/v1alpha1
kind: ResourceClass
metadata:
  creationTimestamp: null
  name: Example
spec:
  apiGroup: example.com
  entries:
  - type:
      group: example.com
      resource: crontabs
      version: v1
