apiVersion: meta.appscode.com/v1alpha1
kind: ResourceClass
metadata:
  creationTimestamp: null
  name: Extension
spec:
  apiGroup: extensions
  editable: false
  entries:
  - optional: true
    type:
      group: extensions
      resource: ingresses
      version: v1beta1
