apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: deploy.aws.upbound.io
    k8s.io/kind: DeploymentConfig
    k8s.io/resource: deploymentconfigs
    k8s.io/version: v1beta1
  name: deploy.aws.upbound.io-v1beta1-deploymentconfigs
spec:
  resource:
    group: deploy.aws.upbound.io
    kind: DeploymentConfig
    name: deploymentconfigs
    scope: Cluster
    version: v1beta1
