apiVersion: meta.appscode.com/v1alpha1
kind: ResourceClass
metadata:
  name: "Service & Discovery"
spec:
  apiGroup: networking.k8s.io
  editable: false
  resources:
  - group: ""
    resource: services
    version: v1
  - group: networking.k8s.io
    resource: ingresses
    version: v1beta1
  - group: voyager.appscode.com
    resource: ingresses
    version: v1beta1
  - group: networking.k8s.io
    resource: networkpolicies
    version: v1
  visible: false
