apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: PodMonitor
    k8s.io/resource: podmonitors
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-podmonitors
spec:
  resource:
    group: monitoring.coreos.com
    kind: PodMonitor
    name: podmonitors
    scope: Namespaced
    version: v1
