apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: Prometheus
    k8s.io/resource: prometheuses
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-prometheuses
spec:
  resource:
    group: monitoring.coreos.com
    version: v1
    name: prometheuses
    kind: Prometheus
    scope: Namespaced
  icons:
  - src: https://cdn.appscode.com/k8s/icons/monitoring.coreos.com/prometheus.svg
    type: image/svg+xml
  connections:
    # - statefulset
    # - service
    - target:
        apiVersion: monitoring.coreos.com/v1
        kind: ServiceMonitor
      type: MatchSelector
      namespacePath: "spec.namespaceSelector"
      selectorPath: "spec.selector"
  keyTargets:
    - apiVersion: v1
      kind: Pod
    - apiVersion: v1
      kind: Service
