apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: ServiceMonitor
    k8s.io/resource: servicemonitors
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-servicemonitors
spec:
  resource:
    group: monitoring.coreos.com
    version: v1
    name: servicemonitors
    kind: ServiceMonitor
    scope: Namespaced
  keyTargets:
    - apiVersion: apps/v1
      kind: ReplicaSet
    - apiVersion: v1
      kind: Pod
    - apiVersion: v1
      kind: Service
  connections:
    # - statefulset
    - target:
        apiVersion: v1
        kind: Service
      type: MatchSelector
      namespacePath: "spec.namespaceSelector"
      selectorPath: "spec.selector"
