apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: appcatalog.appscode.com
    k8s.io/kind: AppBinding
    k8s.io/resource: appbindings
    k8s.io/version: v1alpha1
  name: appcatalog.appscode.com-v1alpha1-appbindings
spec:
  resource:
    group: appcatalog.appscode.com
    kind: AppBinding
    name: appbindings
    scope: Namespaced
    version: v1alpha1
  displayColumns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
