apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: sqs.aws.upbound.io
    k8s.io/kind: QueueRedriveAllowPolicy
    k8s.io/resource: queueredriveallowpolicies
    k8s.io/version: v1beta1
  name: sqs.aws.upbound.io-v1beta1-queueredriveallowpolicies
spec:
  resource:
    group: sqs.aws.upbound.io
    kind: QueueRedriveAllowPolicy
    name: queueredriveallowpolicies
    scope: Cluster
    version: v1beta1
