apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: iam.aws.upbound.io
    k8s.io/kind: UserLoginProfile
    k8s.io/resource: userloginprofiles
    k8s.io/version: v1beta1
  name: iam.aws.upbound.io-v1beta1-userloginprofiles
spec:
  resource:
    group: iam.aws.upbound.io
    kind: UserLoginProfile
    name: userloginprofiles
    scope: Cluster
    version: v1beta1
