apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: extensions
    k8s.io/kind: Scale
    k8s.io/resource: scales
    k8s.io/version: v1beta1
  name: extensions-v1beta1-scales
spec:
  resource:
    group: extensions
    kind: Scale
    name: scales
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-scale-editor
      url: https://bundles.byte.builders/ui/
      version: v0.1.0
  validation:
    openAPIV3Schema:
      description: represents a scaling request for a resource.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          properties:
            annotations:
              additionalProperties:
                type: string
              description: 'Annotations is an unstructured key value map stored with
                a resource that may be set by external tools to store and retrieve
                arbitrary metadata. They are not queryable and should be preserved
                when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations'
              type: object
            labels:
              additionalProperties:
                type: string
              description: 'Map of string keys and values that can be used to organize
                and categorize (scope and select) objects. May match selectors of
                replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
              type: object
            name:
              description: 'Name must be unique within a namespace. Is required when
                creating resources, although some resources may allow a client to
                request the generation of an appropriate name automatically. Name
                is primarily intended for creation idempotence and configuration definition.
                Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
              type: string
            namespace:
              description: "Namespace defines the space within which each name must
                be unique. An empty namespace is equivalent to the \"default\" namespace,
                but \"default\" is the canonical representation. Not all objects are
                required to be scoped to a namespace - the value of this field for
                those objects will be empty. \n Must be a DNS_LABEL. Cannot be updated.
                More info: http://kubernetes.io/docs/user-guide/namespaces"
              type: string
          type: object
        spec:
          description: 'defines the behavior of the scale. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.'
          properties:
            replicas:
              description: desired number of instances for the scaled object.
              format: int32
              type: integer
          type: object
        status:
          description: 'current status of the scale. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
            Read-only.'
          properties:
            replicas:
              description: actual number of observed instances of the scaled object.
              format: int32
              type: integer
            selector:
              additionalProperties:
                type: string
              description: 'label query over pods that should match the replicas count.
                More info: http://kubernetes.io/docs/user-guide/labels#label-selectors'
              type: object
            targetSelector:
              description: 'label selector for pods that should match the replicas
                count. This is a serializated version of both map-based and more expressive
                set-based selectors. This is done to avoid introspection in the clients.
                The string will be in the same format as the query-param syntax. If
                the target type only supports map-based selectors, both this field
                and map-based selector field are populated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors'
              type: string
          required:
          - replicas
          type: object
      type: object
