apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: compute.gcp.upbound.io
    k8s.io/kind: ServiceAttachment
    k8s.io/resource: serviceattachments
    k8s.io/version: v1beta1
  name: compute.gcp.upbound.io-v1beta1-serviceattachments
spec:
  resource:
    group: compute.gcp.upbound.io
    kind: ServiceAttachment
    name: serviceattachments
    scope: Cluster
    version: v1beta1
