apiVersion: meta.appscode.com/v1alpha1
kind: ResourceDescriptor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: networking.k8s.io
    k8s.io/kind: NetworkPolicy
    k8s.io/resource: networkpolicies
    k8s.io/version: v1
  name: networking.k8s.io-v1-networkpolicies
spec:
  resource:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: networkpolicies
    scope: Namespaced
    version: v1
  columns:
    - jsonPath: .metadata.name
      name: Name
      type: string
    - jsonPath: .metadata.namespace
      name: Namespace
      type: string
    - jsonPath: .metadata.labels
      name: Labels
      type: object
    - jsonPath: .metadata.annotations
      name: Annotations
      type: object
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
