apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: devices.azure.upbound.io
    k8s.io/kind: IOTHubDPSCertificate
    k8s.io/resource: iothubdpscertificates
    k8s.io/version: v1beta1
  name: devices.azure.upbound.io-v1beta1-iothubdpscertificates
spec:
  resource:
    group: devices.azure.upbound.io
    kind: IOTHubDPSCertificate
    name: iothubdpscertificates
    scope: Cluster
    version: v1beta1
