name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  k8s:
    name: k8s
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        k8s: [v1.20.15, v1.21.14, v1.22.17, v1.23.17, v1.24.12, v1.25.8, v1.26.3, v1.27.1, v1.28.0, v1.29.0]
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v1
        with:
          go-version: '1.21'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Create Kubernetes ${{ matrix.k8s }} cluster
        id: kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.17.0
          image: kindest/node:${{ matrix.k8s }}

      - name: Prepare Host
        run: |
          sudo apt-get -qq update || true
          sudo apt-get install -y bzr
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Run checks
        run: |
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          kubectl get nodes
          kubectl create -R -f ./crds
          make ci

  # Stub Build check to keep branch protection rules happy
  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: k8s
    steps:
      - name: Build
        run: |
          exit 0
