apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.meta.appscode.com
spec:
  group: meta.appscode.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: default
  version: v1alpha1
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec:
  type: ExternalName
  externalName: api.crd.builders
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
